export const dummy ={
    "jdList": [
        {
            "jdUid": "cfff363b-053c-11ef-83d3-06301d0a7178-92032",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 103,
            "minJdSalary": 86,
            "salaryCurrencyCode": "USD",
            "location": "mumbai",
            "minExp": 10,
            "maxExp": 15,
            "jobRole": "ios",
            "companyName": "Rakuten",
            "logoUrl": "https://logo.clearbit.com/rakuten.com"
        },
        {
            "jdUid": "cfff3648-053c-11ef-83d3-06301d0a7178-92034",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 64,
            "minJdSalary": 25,
            "salaryCurrencyCode": "USD",
            "location": "bangalore",
            "minExp": 2,
            "maxExp": 11,
            "jobRole": "backend",
            "companyName": "Samsung",
            "logoUrl": "https://logo.clearbit.com/samsung.com"
        },
        {
            "jdUid": "cfff3655-053c-11ef-83d3-06301d0a7178-92036",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 37,
            "minJdSalary": 3,
            "salaryCurrencyCode": "USD",
            "location": "remote",
            "minExp": 3,
            "maxExp": 11,
            "jobRole": "android",
            "companyName": "Apple",
            "logoUrl": "https://logo.clearbit.com/apple.com"
        },
        {
            "jdUid": "cfff3662-053c-11ef-83d3-06301d0a7178-92038",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 62,
            "minJdSalary": 31,
            "salaryCurrencyCode": "USD",
            "location": "chennai",
            "minExp": 9,
            "maxExp": 12,
            "jobRole": "tech lead",
            "companyName": "Dell Technologies",
            "logoUrl": "https://logo.clearbit.com/dell.com"
        },
        {
            "jdUid": "cfff3763-053c-11ef-83d3-06301d0a7178-92040",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 69,
            "minJdSalary": 48,
            "salaryCurrencyCode": "USD",
            "location": "delhi ncr",
            "minExp": 10,
            "maxExp": 11,
            "jobRole": "frontend",
            "companyName": "Dropbox",
            "logoUrl": "https://logo.clearbit.com/dropbox.com"
        },
        {
            "jdUid": "cfff3cd9-053c-11ef-83d3-06301d0a7178-92042",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 101,
            "minJdSalary": 100,
            "salaryCurrencyCode": "USD",
            "location": "mumbai",
            "minExp": 10,
            "maxExp": 18,
            "jobRole": "ios",
            "companyName": "Intel Corporation",
            "logoUrl": "https://logo.clearbit.com/intel.com"
        },
        {
            "jdUid": "cfff3cf9-053c-11ef-83d3-06301d0a7178-92044",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 103,
            "minJdSalary": 79,
            "salaryCurrencyCode": "USD",
            "location": "bangalore",
            "minExp": 10,
            "maxExp": 11,
            "jobRole": "backend",
            "companyName": "Cisco",
            "logoUrl": "https://logo.clearbit.com/cisco.com"
        },
        {
            "jdUid": "cfff3d09-053c-11ef-83d3-06301d0a7178-92046",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 16,
            "minJdSalary": 10,
            "salaryCurrencyCode": "USD",
            "location": "remote",
            "minExp": 10,
            "maxExp": 15,
            "jobRole": "android",
            "companyName": "Oracle",
            "logoUrl": "https://logo.clearbit.com/oracle.com"
        },
        {
            "jdUid": "cfff3d16-053c-11ef-83d3-06301d0a7178-92048",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 103,
            "minJdSalary": 93,
            "salaryCurrencyCode": "USD",
            "location": "chennai",
            "minExp": 3,
            "maxExp": 11,
            "jobRole": "tech lead",
            "companyName": "Baidu",
            "logoUrl": "https://logo.clearbit.com/baidu.com"
        },
        {
            "jdUid": "cfff3d23-053c-11ef-83d3-06301d0a7178-92050",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 33,
            "minJdSalary": 13,
            "salaryCurrencyCode": "USD",
            "location": "delhi ncr",
            "minExp": 3,
            "maxExp": 3,
            "jobRole": "frontend",
            "companyName": "Amazon",
            "logoUrl": "https://logo.clearbit.com/amazon.com"
        },
        {
            "jdUid": "cfff359f-053c-11ef-83d3-06301d0a7178-92008",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": null,
            "minJdSalary": 44,
            "salaryCurrencyCode": "USD",
            "location": "chennai",
            "minExp": 7,
            "maxExp": 14,
            "jobRole": "tech lead",
            "companyName": "Olympus",
            "logoUrl": "https://logo.clearbit.com/olympus.com"
        },
        {
            "jdUid": "cfff3d31-053c-11ef-83d3-06301d0a7178-92052",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 78,
            "minJdSalary": 48,
            "salaryCurrencyCode": "USD",
            "location": "mumbai",
            "minExp": 4,
            "maxExp": 8,
            "jobRole": "ios",
            "companyName": "Alibaba",
            "logoUrl": "https://logo.clearbit.com/alibaba.com"
        },
        {
            "jdUid": "cfff3d3e-053c-11ef-83d3-06301d0a7178-92054",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 102,
            "minJdSalary": 76,
            "salaryCurrencyCode": "USD",
            "location": "bangalore",
            "minExp": 8,
            "maxExp": 8,
            "jobRole": "backend",
            "companyName": "GoPro",
            "logoUrl": "https://logo.clearbit.com/gopro.com"
        },
        {
            "jdUid": "cfff3d4b-053c-11ef-83d3-06301d0a7178-92056",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 91,
            "minJdSalary": 62,
            "salaryCurrencyCode": "USD",
            "location": "remote",
            "minExp": 9,
            "maxExp": 10,
            "jobRole": "android",
            "companyName": "Twitter",
            "logoUrl": "https://logo.clearbit.com/twitter.com"
        },
        {
            "jdUid": "cfff3d58-053c-11ef-83d3-06301d0a7178-92058",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 57,
            "minJdSalary": 32,
            "salaryCurrencyCode": "USD",
            "location": "chennai",
            "minExp": 9,
            "maxExp": 14,
            "jobRole": "tech lead",
            "companyName": "ZTE",
            "logoUrl": "https://logo.clearbit.com/zte.com.cn"
        },
        {
            "jdUid": "cfff3d65-053c-11ef-83d3-06301d0a7178-92060",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 22,
            "minJdSalary": 9,
            "salaryCurrencyCode": "USD",
            "location": "delhi ncr",
            "minExp": 10,
            "maxExp": 10,
            "jobRole": "frontend",
            "companyName": "ZTE",
            "logoUrl": "https://logo.clearbit.com/zte.com.cn"
        },
        {
            "jdUid": "cfff3d72-053c-11ef-83d3-06301d0a7178-92062",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 103,
            "minJdSalary": 98,
            "salaryCurrencyCode": "USD",
            "location": "mumbai",
            "minExp": 9,
            "maxExp": 11,
            "jobRole": "ios",
            "companyName": "Netflix",
            "logoUrl": "https://logo.clearbit.com/netflix.com"
        },
        {
            "jdUid": "cfff3d7f-053c-11ef-83d3-06301d0a7178-92064",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 22,
            "minJdSalary": 6,
            "salaryCurrencyCode": "USD",
            "location": "bangalore",
            "minExp": 2,
            "maxExp": 3,
            "jobRole": "backend",
            "companyName": "MasterCard",
            "logoUrl": "https://logo.clearbit.com/mastercard.com"
        },
        {
            "jdUid": "cfff3d8b-053c-11ef-83d3-06301d0a7178-92066",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 50,
            "minJdSalary": 36,
            "salaryCurrencyCode": "USD",
            "location": "remote",
            "minExp": 1,
            "maxExp": 1,
            "jobRole": "android",
            "companyName": "Facebook",
            "logoUrl": "https://logo.clearbit.com/facebook.com"
        },
        {
            "jdUid": "cfff3d98-053c-11ef-83d3-06301d0a7178-92068",
            "jdLink": "https://weekday.works",
            "jobDetailsFromCompany": "This is a sample job and you must have displayed it to understand that its not just some random lorem ipsum text but something which was manually written. Oh well, if random text is what you were looking for then here it is: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages and now in this assignment.",
            "maxJdSalary": 90,
            "minJdSalary": 55,
            "salaryCurrencyCode": "USD",
            "location": "chennai",
            "minExp": 5,
            "maxExp": 8,
            "jobRole": "tech lead",
            "companyName": "HP",
            "logoUrl": "https://logo.clearbit.com/hp.com"
        }
    ],
}